### ISSUE TITLE
Build failure when building specific tag for libtorrent

### ISSUE THREAD

**Issue by darthShadow** [userdocs/qbittorrent-nox-static#36]
The following line needs the `libtorrent_patch_tag` to be prefixed with a `v` when using a specific release tag rather than master.

https://github.com/userdocs/qbittorrent-nox-static/blob/8657dddbe462a83c97b84732cbe3e391ddb877ce/qbittorrent-nox-static.sh#L528

**Comment by userdocs** [comment]
You are going to have to be more specific as I do not really understand your issue.

The reason being, there are two tag formats:

`libtorrent-1.2.10` - older and depreciated.
#
`v1.2.10` - modern and main format moving forward.

I do not understand the need to prefix the `v` when you should be providing it as part of the tag and this is removed by the function since the path generated is numerical.

```
qb-build/patches/libtorrent/1.2.10
```

I cannot see what reason i would need to prefix the `v`

**Comment by darthShadow** [comment]
No, the path for the patch is correct which is what results in the issue. When we strip out the `v` from the patch tag earlier in the function, it breaks the Jamfile url line.

For example, considering the patch tag as 1.2.10, the url for the Jamfile will be:

`https://raw.githubusercontent.com/arvidn/libtorrent/1.2.12/Jamfile` (which gives 404),

when the actual and correct url is:

`https://raw.githubusercontent.com/arvidn/libtorrent/v1.2.12/Jamfile` (Note the additional `v` before the version)

The current behaviour is probably fine for the RC_1_2 & RC_2_0 branches (since they don't have a `v` prefix) but I haven't tried them.

**Comment by userdocs** [comment]
Ok, i see. I introduced the bug, but it's meant to use the RC_2_0 jamfile for tags referencing 1.2 and the RC_1_1 jamfile for tags referencing 1.1

That is how it will be fixed.

**Comment by userdocs** [comment]
CAn you try

**Comment by userdocs** [comment]
Can you test this fix to see if it resolves the issue for you. It worked for me.

https://github.com/userdocs/qbittorrent-nox-static/commit/1a603f628eda97183d76b61e11a9598e26650600

**Comment by userdocs** [comment]
Ok, not that fix, i had to fix that fix. fml. It should be ok now.

**Comment by darthShadow** [comment]
Working now. Thanks.
