### ISSUE TITLE
Conventional naming.

### ISSUE THREAD

**Issue by martadinata666** [userdocs/qbittorrent-nox-static#57]
I love this static build, but i hope we can use conventional naming. `x86_64 to amd64`, `aarch64 to arm64`. The reason is to match TARGETARCH used by docker buildx, to generate single image support amd64 and arm64 image.

**Comment by userdocs** [comment]
Hi and i am glad you like it.  

I currently use the naming convention defined by the supported multi arch build platform Which is Alpine Linux and you can see it here https://alpinelinux.org/downloads/

![image](https://user-images.githubusercontent.com/16525024/131705915-c034d173-7544-48ad-8e5c-c04153e2233f.png)

This is so that I don't have one scheme that I need to rename to just work with Alpine. I won't change that unless Alpine changes it's own naming schemes as it just makes the multibuild part very complex having to rename things just to work with their repository urls.

If you tell me what it is specifically you need I can maybe provide a switch based workaround?

I assume it is the naming of the output file itself?

```bash
x86_64-icu-qbittorrent-nox > am64-icu-qbittorrent-nox
```

I cannot see how changing it internally would help buildx. So can you be specific about what you need?

**Comment by martadinata666** [comment]
yes, as you assume, it just the output name ```x86_64-icu-qbittorrent-nox > amd64-icu-qbittorrent-nox```

So this is my dockerfile of ffmpeg static
```
FROM registry.gitlab.com/dedyms/debian:latest
ARG DATE
ARG TARGETARCH
ARG BUILDPLATFORM
RUN echo "i am running on $BUILDPLATFORM, building for $TARGETARCH"
ENV FFMPEG_BUILD_DATE=$DATE
RUN apt update && apt install -y --no-install-recommends wget xz-utils && apt clean && rm -rf /var/lib/apt/lists*
USER $CONTAINERUSER
WORKDIR /home/$CONTAINERUSER
RUN wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-$TARGETARCH-static.tar.xz && \
    tar -xf ffmpeg-git-$TARGETARCH-static.tar.xz && \
    ls -alh && \
    mv ffmpeg-git-$DATE-$TARGETARCH-static/ffmpeg .local/bin/ && \
    mv ffmpeg-git-$DATE-$TARGETARCH-static/ffprobe .local/bin/ && \
    rm -rf ffmpeg-git-$DATE-$TARGETARCH-static
```
So following the docker buildx command
```
docker buildx build --push --platform linux/arm64,linux/amd64 --build-arg DATE=$DATE -t "$CI_REGISTRY_IMAGE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE" -t "$CI_REGISTRY_IMAGE:$DATE" -t "$CI_DOCKERHUB_REGISTRY_IMAGE:$DATE" . -f Dockerfile
```

The `TARGETARCH` will result `amd64` or `arm64` based on platform, then it will download based on the name, `ffmpeg-git-amd64-static.tar.xz` or `ffmpeg-git-arm64-static.tar.xz`. That's my insight on this.

**Comment by userdocs** [comment]
What you can do is use your own release naming via cloning the repo and using this action file matrix

https://github.com/userdocs/qbittorrent-nox-static/blob/master/.github/workflows/matrix_multi_build_and_release.ym

This are the lines that is naming renaming and uploading the release asset

https://github.com/userdocs/qbittorrent-nox-static/blob/master/.github/workflows/matrix_multi_build_and_release.yml#L92
https://github.com/userdocs/qbittorrent-nox-static/blob/master/.github/workflows/matrix_multi_build_and_release.yml#L98

**Comment by martadinata666** [comment]
thanks for the suggestion, the reason i closed this because i found that Dockerfile can use `if` condition based on `TARGETARCH` to download respective binaries.

```
RUN if [ "${TARGETARCH}" = "amd64" ]; then \
        wget https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-$QBVERSION\_v$LIBTORRENT/x86_64-qbittorrent-nox && \
        mv ./x86_64-qbittorrent-nox /home/$CONTAINERUSER/.local/bin/qbittorrent-nox; \
    fi;

RUN if [ "${TARGETARCH}" = "arm64" ]; then \
        wget https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-$QBVERSION\_v$LIBTORRENT/aarch64-qbittorrent-nox && \
        mv ./aarch64-qbittorrent-nox /home/$CONTAINERUSER/.local/bin/qbittorrent-nox; \
    fi;
```

Again, thanks for the binary release it really helps.
